---

- name: prom2teams | Install
  import_tasks: install.yml
  tags:
    - install

- name: prom2teams | Config
  import_tasks: config.yml
  tags:
    - config

- name: prom2teams | Service
  import_tasks: service.yml
  tags:
    - service
